FileVersion = 1
Projects = {beef-interop-lib = {Path = "beef-interop-lib"}, dummy = {Path = "dummy"}}

[Workspace]
StartupProject = "dummy"

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
