FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["beef-interop-lib\\src\\Lib.bf", "dummy\\src\\Program.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Attribute.bf"]

[MainWindow]
X = 505
Y = 103
Width = 1549
Height = 1162
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 450.0
RequestedHeight = 300.0
SizePriority = 300.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 300.0
RequestedHeight = 300.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 1.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 92.66666
Type = "SourceViewPanel"
FilePath = "dummy\\src\\Program.bf"
CursorPos = 143
ProjectName = "dummy"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Lib.bf"
TabWidth = 60.66667
Type = "SourceViewPanel"
FilePath = "beef-interop-lib\\src\\Lib.bf"
CursorPos = 236
ProjectName = "beef-interop-lib"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 375.0
RequestedHeight = 375.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 375.0
RequestedHeight = 375.0
SizePriority = 0.4874902
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Profile"
TabWidth = 86.66666
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.33334
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.33334
Type = "WatchPanel"
Columns = [{Width = 300.0}, {Width = 300.0}, {Width = 300.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto"
TabWidth = 76.66666
Type = "AutoWatchPanel"
Columns = [{Width = 300.0}, {Width = 300.0}, {Width = 300.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 375.0
RequestedHeight = 375.0
SizePriority = 0.5125098
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.66666
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.3333
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 89.33334
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""
